---
# Title: role-certbot-apache2
#
# Author: Bitfinity-NL / L. Rutten
# File: defaults/main.yml
#
# Description:
#   Request letsencrypt certificate for Apache2.

- name: "restart_ufw"
  systemd:
    state: restarted
    name: ufw

- name: "reload_apache2"
  systemd:
    state: reloaded
    name: apache2
